import { Providers } from "@/app/providers";
import { AddSchedule, Navbar } from "@/components";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="container mx-auto min-h-screen">
            <Navbar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
